In [1]:
pip list

Package           Version
----------------- -----------
asttokens         3.0.1
colorama          0.4.6
comm              0.2.3
debugpy           1.8.17
decorator         5.2.1
exceptiongroup    1.3.1
executing         2.2.1
ipykernel         7.1.0
ipython           8.37.0
jedi              0.19.2
jupyter_client    8.6.3
jupyter_core      5.9.1
matplotlib-inline 0.2.1
nest-asyncio      1.6.0
numpy             2.2.6
packaging         25.0
parso             0.8.5
pip               21.2.3
platformdirs      4.5.0
prompt_toolkit    3.0.52
psutil            7.1.3
pure_eval         0.2.3
Pygments          2.19.2
python-dateutil   2.9.0.post0
pyzmq             27.1.0
setuptools        57.4.0
six               1.17.0
stack-data        0.6.3
tornado           6.5.2
traitlets         5.14.3
typing_extensions 4.15.0
wcwidth           0.2.14
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\devid\Desktop\Nexperts Academy\AI and ML for Beginners Repo\.venv\Scripts\python.exe -m pip install --upgrade pip' command.


In [3]:
pip install pandas

  Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
  Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\devid\Desktop\Nexperts Academy\AI and ML for Beginners Repo\.venv\Scripts\python.exe -m pip install --upgrade pip' command.


In [4]:
import pandas as pd

In [ ]:
#pip install numpy
 
import numpy as np

np.__version__ 

'2.2.6'

In [2]:
import array as ar

array1 = ar.array("i",[1,2,3,4,5,6])
type(array1)


array.array

In [10]:
arraynp = np.array([1,2,3,4,5,6,7,8,9,10])
# numpy lets us create nd arrays
type(arraynp)

array1D = np.array([1,2,3])
array1D
# 1 Dimensional Arrays - These are also called Vectors 
print("this is a ",array1D.ndim, "dimensional array")

this is a  1 dimensional array


In [13]:
array2D = np.array([[1,2,3],[1,2,3]])
print(array2D)
print("\nthis is a ",array2D.ndim, "dimensional array")

[[1 2 3]
 [1 2 3]]

this is a  2 dimensional array


In [ ]:
array3D = np.array([[[1,2,3],[1,2,3],[1,2,3]],
                    [[1,2,3],[1,2,3],[1,2,3]],
                    [[1,2,3],[1,2,3],[1,2,3]]])

In [ ]:
array3D = np.array([[[1],[2],[3]],
                    [[4],[5],[6]],
                    [[7],[8],[9]]])
print(array3D)
print("\nthis is a ",array3D.ndim, "dimensional array")

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]

this is a  3 dimensional array


In [27]:
# 1 2 3
# 4 5 6
# 7 8 9 

array19 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print(array19,"\n\n",array19.ndim)



[[1 2 3]
 [4 5 6]
 [7 8 9]] 

 2


In [ ]:
list1D = [1,2,3]

print(list1D*10)

print(array1D*10) # numpy arrays
# element wise operations
# broadcast

A = np.array([[1, 2, 3],
              [4, 5, 6]]) 

B = np.array([[1, 2, 3],
              [4, 5, 6],
              [4, 5, 6]]) 
# array1D = np.array([1,2,3])
print(A.shape,B.shape)


# A * B

np.matmul(A,B) # matrix multiply

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[10 20 30]
(2, 3) (3, 3)


array([[21, 27, 33],
       [48, 63, 78]])