# $Neural-Networks$

A neural network extends the **perceptron** by connecting many neurons across multiple layers.
- When you connect multiple Perceptrons, you get **MLP (Multi-Layer Perceptron)** and **DNN (Deep Neural Network)**
- can be used interchangeably but there are some differences

#### MLP vs DNN

- MLP is considered an example of DNNs. Other examples of DNNs can be found in Convolutional Neural Networks (CNN) and Recurrent Neural Networks (RNN)
- A small number of hidden layers in MLP vs	High number of hidden layers DNNs

![](https://miro.medium.com/proxy/1*eloYEyFrblGHVZhU345PJw.jpeg)

1. **Input layer:** The input layer provides the network with the raw feature vector:

- x = (x1, x2, x3, ..., xn)
- Is not a bunch on neurons
- No computation happens here
- It simply passes the input values to the next layer

2. **Hidden layers:** Hidden layers contain multiple perceptrons (neurons) that learn **intermediate representations** of the data.

- 
- 
- 
- Some libraries even create IR files for optimization purposes

3. **Output layer:** The output layer produces the final prediction, which may be binary, multi-class or a continuous value.

In [2]:
# Create a simple MLP
import numpy as np

# another activation function --- step activation function
def unit_step_activation(weighted_sum_bias):
    z = weighted_sum_bias
    if z >= 0:
        return 1
    else:
        return 0

In [ ]:
# NN with 1 hidden neuron

inputs = np.array([  0,    1,    0,    1,    0])

# Hidden Layer
W1 = np.array([0.7,  0.0,  0.8,  -0.2,  0.1])
b1 = 0
z1 = sum(inputs * W1) + b1   # add some bias as well   

a1 = unit_step_activation(z1)


# Output Layer
W2 = np.array([0.7,  0.6,  0.8,  0.2,  0.1])
b2 = 0
z2 = sum(a1 * W2) + b2   # add some bias as well

y = unit_step_activation(z2)

if y==1:
    print("we GO!!")
else:
    print("We Don't go!!!")

we GO!!


#### We can implement sum as well, using the dot operation
- using the matrix multiplication
- 
- To multiply an m×n matrix by an n×p matrix, the ns must be the same,
and the result is an m×p matrix

In [18]:
# matrix multiplication

# single row ===== VECTOR
mat1 = np.array([1,2,3,4,5]) # 1 x 5

mat2 = np.array([[1,1,1],
                [2,2,2],
                [1,1,1],
                [1,1,1],
                [2,2,2]]) # 5 x 3

np.dot(mat1, mat2)



array([22, 22, 22])

In [ ]:
# single row ===== VECTOR
mat1 = np.array([1,2,3]) # 1 x 3 ---- 3 x 1


mat2 = np.array([[1,2,3],
                [2,2,2]]) # 2 x 3

mat3 = np.array([[1,2],
                [2,2],
                [2,2]]) # 3 x 2

# mat1@mat2 # matrix operation
np.dot(mat2, mat1) # 1 x 3 ----> 2 x 3
# this normally does not work, but in python, the single dimension will operate on this


array([14, 12])

#### We need activation functions for neural networks

In [ ]:
# another activation function --- step activation function
def unit_step_activation(z):
    return np.where(z>= 0, 1, 0)

In [ ]:
unit_step_activation(np.array([1,1,-1,-3, 2,2]))

array([1, 1, 0, 0, 1, 1])

### NN with 3 hidden neurons

In [ ]:
# step 1: Input Layer (5 features)
inputs = np.array([  0,    1,    0,    1,    0])

# step2: Hidden Layer (3 Neurons)

# what should be the dimensions of weight matrix?
# 5 inputs x 3 neurons = 5rows x 3columns

# weight matrix of first hidden layer
h1 = np.array([
    [0.3, 0.2, 0.4],
    [0.3, 0.1, 0.4],
    [0.7, 0.2, 0.8],
    [0.2, 0.5, 0.4],
    [0.2, 0.2, 0.4]
])
b1 = np.array([0, 0, 0])
z1 = np.dot(inputs, h1) + b1
a1 = unit_step_activation(z1)

# step 3: output layer
# 3 inputs from hidden layer, 1 output neuron
# weight matrix shape ---> 3 , 1

# row vector
# output = np.array([0.2,0.2,0.4])

# column vector
output = np.array([
     [0.2], 
     [0.2], 
     [0.4]
])
b2 = np.array([0])
z2 = np.dot(a1, output) + b2 
# now a1 = 1 x 3 and output = 3 x 1
# numpy is funny, and will give you three output, no matter what you do

y = unit_step_activation(z2)

if y == 1:
    print('We GO!!!!!')
else:
    print("We don't go!!!")

We GO!!!!!


### Shapes of matrixes involved:
- if i had 3 neurons, in hidden layer, weight matrix =====> shape was (inputs, number of neurons) ---- 5 x 3
- output of this hidden layer was --- number of neurons ---- 3
- 
- 
- if i had 1 neuron in output layer, weight matrix ====> shape was (3 inputs, 1 output neuron) --- 3 x 1 -- simply a **column vector**
- output will be number neurons of output layer --- 1
- 

Resources:
- https://medium.com/deep-learning-demystified/introduction-to-neural-networks-part-1-e13f132c6d7e
- 

# A simple MLP - Vanilla Neural Network

In [ ]:
import numpy as np

# Activation function (Sigmoid) and its derivative
def sigmoid(x):
return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
return x * (1 - x)

# Input data (X) and target output (Y)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0], [1], [1], [0]])

# Initialize weights and biases
np.random.seed(42)
input_layer_neurons = X.shape[1]
hidden_layer_neurons = 4
output_neurons = 1

weights_input_hidden = np.random.uniform(size=(input_layer_neurons, hidden_layer_neurons))
weights_hidden_output = np.random.uniform(size=(hidden_layer_neurons, output_neurons))
bias_hidden = np.random.uniform(size=(1, hidden_layer_neurons))
bias_output = np.random.uniform(size=(1, output_neurons))

# Training the network
epochs = 10000
learning_rate = 0.1

for _ in range(epochs):
# Forward pass
hidden_layer_input = np.dot(X, weights_input_hidden) + bias_hidden
hidden_layer_output = sigmoid(hidden_layer_input)
output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
predicted_output = sigmoid(output_layer_input)

# Backpropagation
error = Y - predicted_output
d_predicted_output = error * sigmoid_derivative(predicted_output)
error_hidden_layer = d_predicted_output.dot(weights_hidden_output.T)
d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

# Update weights and biases
weights_hidden_output += hidden_layer_output.T.dot(d_predicted_output) * learning_rate
weights_input_hidden += X.T.dot(d_hidden_layer) * learning_rate
bias_output += np.sum(d_predicted_output, axis=0, keepdims=True) * learning_rate
bias_hidden += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate

# Output the final predictions
print("Predicted Output:")
print(predicted_output)