# $$Tensors$$

- We have already learnt about arrays
- We used NumPy to build array objects
- 
- Arrays helped us create `matrix`
- 

Tensor 
- a container for `numbers`
- is the fundamental building block of modern ML
- 
- A tensor is **a generalization of vectors and matrices** and is easily understood as a **multidimensional array**.
- 
- very similar to NumPy arrays but:
    - Pytorch tensors can store Gradients
    - They can be moved to GPU if needed
- that means we can use parallel processing, we can use graphics cards to process data from tensors
- this makes tensors faster than arrays or any such data structure
- 
- think of tensors as somthing that came after we already knew about vectors and matricies 
- 


- a generalization of vectors and matrices
- ![](https://cdn-images-1.medium.com/max/2000/1*_D5ZvufDS38WkhK9rK32hQ.jpeg)
    - 0D Tensor - Scalar - zero-order tensor -  Rank 0 Tensor - eg. Numbers
    - 1D Tensor - Vector - first-order tensor -  Rank 1 Tensor - eg. List of Numbers
    - 2D Tensor - Matrix - second-order tensor -  Rank 2 Tensor - eg. a table, data with columns
    - 3D Tensor - Tensor - higher-order tensors -  Rank 3 Tensor - eg. Color Images (RGB)
    - 4D Tensor - Tensor - higher-order tensors -  Rank 4 Tensor - eg. 

    A scalar is zero-order tensor or rank zero tensor. A vector is a one-dimensional or first order tensor, and a matrix is a two-dimensional or second order tensor

- Multiple ways of creating tensors
- We use:
    1. Tensorflow
    2. PyTorch

In [ ]:
# PyTorch
import torch
import numpy as np

tensor0 = torch.tensor(5) # Scalar - Rank 0 Tensor
type(tensor0)

tensor1 = torch.tensor([1,2,3,4]) # Vector - Rank 1 Tensor


for i in tensor1:
    print(i)

tensor(1)
tensor(2)
tensor(3)
tensor(4)
tensor(4)
tensor([1, 2, 3])


In [ ]:
tensor2 = torch.tensor( # Matrix - Rank 2 Tensor
    [[1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4]]
) 

tensor2.shape # [6,4]

tensor2.ndim # dimensions


2

In [ ]:
tensor3 = torch.tensor( # 3D matrix - Rank 3 Tensor
    [[[1,2,3],
    [1,2,3]], 
    [[1,2,3],
    [1,2,3]],
    [[1,2,3],
    [1,2,3]],
    [[1,2,3],
    [1,2,3]]]
    ) 

tensor3.ndim

tensor3.shape # [4, 2, 3]



torch.Size([4, 2, 3])

In [46]:
# Accessing elements in tensors
# slicing
tensor1[0:3]
tensor1[1:3]


tensor1[0:4:2]

# indexing --- [rows, columns] 
tensor2[3,2]
tensor2[0:3, 0:2]

tensor([[1, 2],
        [1, 2],
        [1, 2]])

In [50]:
# comprehension works
tensor2d = torch.tensor([x for x in range(10)])

# boolean masking
tensor2da =  tensor2d[tensor2d > 5]

tensor2da

tensor([6, 7, 8, 9])

In [82]:
# random
tensor3d = torch.rand(2,3,4)

# torch.random.manual_seed(10)
tensor3d = torch.randint(0, 100, (2,2)) # start, stop, (shape)

tensor3d

tensor([[ 2, 72],
        [12, 37]])

In [108]:
# Ellipsis
# is used later in DL

np.random.seed(42)
arry6D = np.random.randint(0,10, (5,5,5,4,6,7))

# what if we want to only get a couple of dimensions
arry6D[0:4,:,:,:,:,0:3]
arry6D[0:4,..., 0:3]
arry6D[None,..., None]

array([[[[[[[[6],
             [3],
             [7],
             ...,
             [6],
             [9],
             [2]],

            [[6],
             [7],
             [4],
             ...,
             [7],
             [7],
             [2]],

            [[5],
             [4],
             [1],
             ...,
             [5],
             [1],
             [4]],

            [[0],
             [9],
             [5],
             ...,
             [0],
             [9],
             [2]],

            [[6],
             [3],
             [8],
             ...,
             [4],
             [2],
             [6]],

            [[4],
             [8],
             [6],
             ...,
             [3],
             [8],
             [1]]],


           [[[9],
             [8],
             [9],
             ...,
             [1],
             [3],
             [6]],

            [[7],
             [2],
             [0],
             ...,
             [1],
            

In [ ]:
torch.random.manual_seed(42)
tensor6 = torch.randint(0,10, (5,5,5,4,6,7))

# what if we want to only get a couple of dimensions
tensor6[0:4,:,:,:,:,0:3]

# will skip the dimension inbetween
tensor6[0:4,..., 0:3]
tensor6[None,..., None]

tensor([[[[[[[[2],
              [7],
              [6],
              ...,
              [6],
              [5],
              [0]],

             [[4],
              [0],
              [3],
              ...,
              [4],
              [0],
              [4]],

             [[1],
              [2],
              [5],
              ...,
              [7],
              [6],
              [9]],

             [[6],
              [3],
              [1],
              ...,
              [3],
              [1],
              [9]],

             [[7],
              [9],
              [2],
              ...,
              [5],
              [9],
              [3]],

             [[4],
              [9],
              [6],
              ...,
              [0],
              [6],
              [2]]],


            [[[7],
              [9],
              [7],
              ...,
              [3],
              [4],
              [3]],

             [[7],
              [0],
              [

In [ ]:
# reshape

tensor2.reshape(12,2) # 4,6 ----> 
tensor2.view(12,2)

tensor2.flatten() # turn it into 1D


tensor([[1, 2, 3, 4]])

Squeeze unsqueeze, will let you deal with the dimensions of the data
- Most neural networks expect inputs:
- `[batch_size, channels, height, width]` # image like data
- if you load a single image ---> [3, 24, 24]
- 
- Squeeze
    - if dimension has a size of 1, removes it
    - if greater than 1, do nothing

In [ ]:
t.squeeze()

In [ ]:
t.unsqueeze()

In [ ]:
image = torch.randn(3, 24, 24) # 3, 24, 24]

input_batch = image.unsqueeze(0) # an added dimension # [1, 3, 24, 24]

input_batch.shape

In [ ]:
unsqz_tensor1 = tensor1.unsqueeze(0) # expand_dims() in numpy
unsqz_tensor1 = tensor1.unsqueeze(1) # transpose

columnvector = tensor1[:, None]
rowvector = tensor1[None, :]


In [ ]:
unsqz_tensor2 = tensor2.unsqueeze(0)  # [6, 4]
unsqz_tensor2 = tensor2.unsqueeze(1)  # [6, 4]
tensor2.shape

In [ ]:
# broadcasting + - * / 
# exactly as we did in numpy

torch.Size([1, 3, 24, 24])

#### Tensors in tensorflow

In [173]:
import tensorflow as tf

tensortf = tf.constant(5)
tensortf1 = tf.constant([1,2,3,4,5])

tensortf2 = tf.constant( # Matrix - Rank 2 Tensor
    [[1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4]]
) 

print(tensortf2)

tf.Tensor(
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]], shape=(6, 4), dtype=int32)


In [174]:
# random tensors

tf.random.uniform([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.7122675 , 0.08473027, 0.00946259],
       [0.23635697, 0.86141896, 0.9961542 ],
       [0.1721909 , 0.6821244 , 0.88077736]], dtype=float32)>

Difference between Tensors in 
PyTorch | Tensorflow
---|---
tensors are intuitive. behave like standard python library | have  a learning curve, but integration with Keras has made it much easier
top of academic research, any new tech | is top of industry, deploying models on devices
third party tools to visualize | built in TensorBoard to create dashboards to track model performance
